### ISSUE TITLE
Doesn't work for me, not been updated in months...

### ISSUE THREAD

**Issue by mschwartz** [edc1591/node-appletv#19]
Thanks for making this, but I'm having trouble getting it to work.

Ubuntu 18,10

```
npm start

> appletv-microservice@1.0.0 start /home/mschwartz/github/RoboDomo/appletv-microservice
> node ./index.js

*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[Function: scan]
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo -3008
    at errnoException (/home/mschwartz/github/RoboDomo/appletv-microservice/node_modules/mdns/lib/resolver_sequence_tasks.js:199:11)
    at getaddrinfo_complete (/home/mschwartz/github/RoboDomo/appletv-microservice/node_modules/mdns/lib/resolver_sequence_tasks.js:112:10)
    at GetAddrInfoReqWrap.oncomplete (/home/mschwartz/github/RoboDomo/appletv-microservice/node_modules/mdns/lib/resolver_sequence_tasks.js:120:9)
Emitted 'error' event at:
    at on_resolver_done (/home/mschwartz/github/RoboDomo/appletv-microservice/node_modules/mdns/lib/browser.js:28:14)
    at next (/home/mschwartz/github/RoboDomo/appletv-microservice/node_modules/mdns/lib/browser.js:100:7)
    at /home/mschwartz/github/RoboDomo/appletv-microservice/node_modules/mdns/lib/resolver_sequence_tasks.js:160:11
    at getaddrinfo_complete (/home/mschwartz/github/RoboDomo/appletv-microservice/node_modules/mdns/lib/resolver_sequence_tasks.js:112:7)
    at GetAddrInfoReqWrap.oncomplete (/home/mschwartz/github/RoboDomo/appletv-microservice/node_modules/mdns/lib/resolver_sequence_tasks.js:120:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appletv-microservice@1.0.0 start: `node ./index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the appletv-microservice@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mschwartz/.npm/_logs/2019-02-11T17_53_45_234Z-debug.log
```

**Comment by mschwartz** [comment]
I forked the repo and added a catch in the right place in the browser logic.
